language: node_js
node_js:
  - "8.9.3"
script:
  - echo "Deploying!"
install:
 - npm install
 - npm install -g firebase-tools
 - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
