//hello
export const HELLO = 'HELLO'

//user
export const UPDATE_USER = 'UPDATE_USER'

//sidenav
export const CLOSE_SIDENAV = 'CLOSE_SIDENAV'
export const OPEN_SIDENAV = 'OPEN_SIDENAV'
export const TOGGLE_SIDENAV = 'TOGGLE_SIDENAV'

//cards
export const UPDATE_CARDS = 'UPDATE_CARDS'
export const ADD_CARD = 'ADD_CARD'
export const SET_ACTIVE_CARD = 'SET_ACTIVE_CARD'

//editCard
export const UPDATE_CARDNAME = 'UPDATE_CARDNAME'
export const UPDATE_CARDIMAGE = 'UPDATE_CARDIMAGE'
export const UPDATE_CARDIMAGEURL = 'UPDATE_CARDIMAGEURL'
export const UPDATE_CARDCOST = 'UPDATE_CARDCOST'
export const UPDATE_ORBTYPE1 = 'UPDATE_ORBTYPE1'
export const UPDATE_ORBTYPE2 = 'UPDATE_ORBTYPE2'
export const UPDATE_ORBTYPE3 = 'UPDATE_ORBTYPE3'
export const UPDATE_ORBTYPE4 = 'UPDATE_ORBTYPE4'
export const UPDATE_CHARGE = 'UPDATE_CHARGE'
export const UPDATE_ENTITYCOUNT = 'UPDATE_ENTITYCOUNT'
export const UPDATE_ENTITYNAME = 'UPDATE_ENTITYNAME'
export const UPDATE_DAMAGETYPE = 'UPDATE_DAMAGETYPE'
export const UPDATE_DAMAGE = 'UPDATE_DAMAGE'
export const UPDATE_HEALTHTYPE = 'UPDATE_HEALTHTYPE'
export const UPDATE_HEALTH = 'UPDATE_HEALTH'
export const UPDATE_EDITIONSYMBOL = 'UPDATE_EDITIONSYMBOL'
export const UPDATE_AFFINITY = 'UPDATE_AFFINITY'
export const UPDATE_SPELLICON1 = 'UPDATE_SPELLICON1'
export const UPDATE_SPELLICON2 = 'UPDATE_SPELLICON2'
export const UPDATE_SPELLICON3 = 'UPDATE_SPELLICON3'
export const UPDATE_SPELLICON4 = 'UPDATE_SPELLICON4'
export const UPDATE_SPELLNAME1 = 'UPDATE_SPELLNAME1'
export const UPDATE_SPELLNAME2 = 'UPDATE_SPELLNAME2'
export const UPDATE_SPELLNAME3 = 'UPDATE_SPELLNAME3'
export const UPDATE_SPELLNAME4 = 'UPDATE_SPELLNAME4'
